@baseUrl = http://localhost:8080

### Teste do endpoint /hello
GET {{baseUrl}}/hello

### 1. Listar médicos (Básico)
GET {{baseUrl}}/medicos

### 2. Listar médicos com paginação
GET {{baseUrl}}/medicos?page=0&size=3

### 3. Listar médicos ordenados por nome
GET {{baseUrl}}/medicos?sort=nome

### 4. Combinar paginação + ordenação
GET {{baseUrl}}/medicos?page=0&size=3&sort=nome

### Teste do endpoint para cadastrar um medico
POST {{baseUrl}}/medicos
Content-Type: application/json

{
  "nome": "Bruno Nogueira Lopes",
  "email": "bruno.lopes@voll.med",
  "crm": "991122",
  "telefone": "71999881234",
  "especialidade": "ORTOPEDIA",
  "endereco": {
    "logradouro": "Av. Sete de Setembro",
    "bairro": "Campo Grande",
    "cep": "40080000",
    "cidade": "Salvador",
    "uf": "BA",
    "numero": "45",
    "complemento": "Consultório 2"
  }
}

### Teste do endpoint para atualizar um medico
PUT {{baseUrl}}/medicos
Content-Type: application/json

{
  "id": 1,
  "nome": "Rodrigo Ferreira",
  "telefone": "6598455656",
  "endereco": {
    "logradouro": "rua 1",
    "bairro": "bairro",
    "cep": "12345678",
    "cidade": "Brasilia",
    "uf": "DF",
    "numero": "1",
    "complemento": "complemento"
  }
}

### Teste do endpoint para deletar um médico
DELETE {{baseUrl}}/medicos/31


### Teste do endpoint para detalhar um médico
GET {{baseUrl}}/medicos/32


### Teste do endpoint para cadastrar pacientes
POST {{baseUrl}}/pacientes
Content-Type: application/json

{
  "nome": "Rodrigo Nascimento Pires",
  "email": "rodrigo.pires@example.com",
  "cpf": "513.804.720-17",
  "telefone": "(67) 98122-0091",
  "endereco": {
    "logradouro": "Avenida Brasil",
    "bairro": "Dom Bosco",
    "cep": "79104320",
    "cidade": "Campo Grande",
    "uf": "MS",
    "numero": "1540",
    "complemento": null
  }
}

### 1. Listar pacientes (Básico)
GET {{baseUrl}}/pacientes

### 2. Listar pacientes com paginação
GET {{baseUrl}}/pacientes?page=0&size=3

### 3. Listar pacientes ordenados por nome
GET {{baseUrl}}/pacientes?sort=nome

### 4. Combinar paginação + ordenação
GET {{baseUrl}}/pacientes?page=0&size=3&sort=nome

### Teste do endpoint para atualizar um paciente
PUT {{baseUrl}}/pacientes
Content-Type: application/json

{
  "id": 1,
  "nome": "Mariana Duarte Leal",
  "email": "mariana.leal@example.com",
  "cpf": "247.915.680-42",
  "telefone": "(48) 99812-4402",
  "endereco": {
    "logradouro": "Rua das Acácias",
    "bairro": "Centro",
    "cep": "88010001",
    "cidade": "Florianópolis",
    "uf": "SC",
    "numero": "112",
    "complemento": "Apto 303"
  }
}

### Teste do endpoint para deletar um paciente
DELETE {{baseUrl}}/pacientes/1

### Teste do endpoint para detalhar um paciente
GET {{baseUrl}}/pacientes/2
