@baseUrl = http://localhost:8080

### Teste do endpoint /hello
GET {{baseUrl}}/hello

### 1. Listar médicos (Básico)
GET {{baseUrl}}/medicos

### 2. Listar médicos com paginação
GET {{baseUrl}}/medicos?page=0&size=3

### 3. Listar médicos ordenados por nome
GET {{baseUrl}}/medicos?sort=nome

### 4. Combinar paginação + ordenação
GET {{baseUrl}}/medicos?page=0&size=3&sort=nome

### Teste do endpoint para cadastrar um medico
POST {{baseUrl}}/medicos
Content-Type: application/json

{
  "nome": "Joana Martins Ribeiro",
  "email": "joana.ribeiro@voll.med",
  "crm": "334455",
  "telefone": "48999887766",
  "especialidade": "GINECOLOGIA",
  "endereco": {
    "logradouro": "Rua das Laranjeiras",
    "bairro": "Centro",
    "cep": "88020000",
    "cidade": "Florianópolis",
    "uf": "SC",
    "numero": "220",
    "complemento": "Apto 304"
  }
}

### Teste do endpoint para atualizar um medico
PUT {{baseUrl}}/medicos
Content-Type: application/json

{
  "id": 1,
  "nome": "Rodrigo Ferreira",
  "telefone": "6598455656",
  "endereco": {
    "logradouro": "rua 1",
    "bairro": "bairro",
    "cep": "12345678",
    "cidade": "Brasilia",
    "uf": "DF",
    "numero": "1",
    "complemento": "complemento"
  }
}

### Teste do endpoint para deletar um médico
DELETE {{baseUrl}}/medicos/31
