@baseUrl = http://localhost:8080

### Teste do endpoint /hello
GET {{baseUrl}}/hello

### Teste do endpoint para cadastrar um medico
POST {{baseUrl}}/medicos
Content-Type: application/json

{
"nome": "Rodrigo Ferreira",
"email": "rodrigo.ferreira@voll.med",
"crm": "123456",
"especialidade": "ORTOPEDIA",
"endereco": {
    "logradouro": "rua 1",
    "bairro": "bairro",
    "cep": "12345678",
    "cidade": "Brasilia",
    "uf": "DF",
    "numero": "1",
    "complemento": "complemento"
    }
}